---
default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      # I don't think this works with pre-commit.ci
      # - id: poetry-lock
      #   always_run: true
      - id: poetry-check
        always_run: true
      - id: poetry-export
        always_run: true
        additional_dependencies:
          - poetry-plugin-export
        args:
          - -f
          - requirements.txt
          - -o
          - requirements.txt

  - repo: https://github.com/worgarside/pre-commit-hooks-dependency-sync
    rev: 1.1.2
    hooks:
      - id: sync-additional-dependencies

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.4
    hooks:
      - id: ruff-format
      - id: ruff

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.1
    hooks:
      - id: actionlint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=1000
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        args:
          - --no-sort-keys
          - --autofix
          - --indent
          - '2'
      - id: trailing-whitespace

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args:
          - --mapping
          - '2'
          - --sequence
          - '4'
          - --offset
          - '2'
          - --width
          - '4096'

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args:
          - --format
          - parsable
          - --strict

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        args:
          - --strict
          - --show-error-codes
        additional_dependencies:
          - pydantic==2.8.2
          - wg-utilities==5.15.4
          - youtube-dl-nightly==2024.7.25
          - Pillow==10.4.0
          - httpx==0.27.0
          - types-RPi.GPIO
          - ffmpeg-python==0.2.0

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli==2.0.1

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.11
    hooks:
      - id: vulture

  - repo: https://github.com/fredrikaverpil/creosote
    rev: v3.0.2
    hooks:
      - id: creosote
